---
  - name: copy
    become: true
    copy:
      src:  /root/project/artifact.tar.gz
      dest: /home/ubuntu/artifact.tar.gz 
      

  - name: Start PM2
    become: true
    shell: |
      cd /home/ubuntu/
      mkdir backend
      cd backend
      tar xzf /home/ubuntu/artifact.tar.gz 
      echo " in backend folder ..f oll files"
      ls
      npm install
      npm run build
      pm2 start npm -- start